[package]
authors = ["Kristoffer Str√∂m <kristoffer@rymdkoloni.se>"]
edition = "2018"
name = "canonical_host"
version = "0.1.0"

[dependencies]
lazy_static = "*"
parking_lot = "*"
canonical = { path = "../canon" }
canonical_derive = { path = "../canon_derive" }
wasmi = "0.6.0"

[dev-dependencies]
counter = { path = "examples/counter", features = ["host"] }
storage = { path = "examples/storage", features = ["host"] }